package com.example.demo.bean;

import java.util.Date;

public class UsercoreUserRegister extends UsercoreUserRegisterKey {
    /**  */
    private static final long serialVersionUID = -7443492758972314687L;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usercore_user_register.PASSWORD
     *
     * @mbggenerated
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usercore_user_register.NICK
     *
     * @mbggenerated
     */
    private String nick;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usercore_user_register.USER_TYPE
     *
     * @mbggenerated
     */
    private String userType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usercore_user_register.IF_BINDCARD
     *
     * @mbggenerated
     */
    private String ifBindcard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usercore_user_register.IF_REALNAME
     *
     * @mbggenerated
     */
    private String ifRealname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usercore_user_register.IF_ACCOUNT
     *
     * @mbggenerated
     */
    private String ifAccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usercore_user_register.IF_FIRSTBUY
     *
     * @mbggenerated
     */
    private String ifFirstbuy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usercore_user_register.IF_PAYPWD
     *
     * @mbggenerated
     */
    private String ifPaypwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usercore_user_register.SEC_LEVEL
     *
     * @mbggenerated
     */
    private String secLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usercore_user_register.USER_LEVEL
     *
     * @mbggenerated
     */
    private String userLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usercore_user_register.STATUS
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usercore_user_register.CREATE_TIME
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usercore_user_register.UPDATE_TIME
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usercore_user_register.OPERATOR
     *
     * @mbggenerated
     */
    private String operator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usercore_user_register.REFEREE
     *
     * @mbggenerated
     */
    private String referee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usercore_user_register.LOGO
     *
     * @mbggenerated
     */
    private String logo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usercore_user_register.CHANNEL_NUM
     *
     * @mbggenerated
     */
    private String channelNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usercore_user_register.TERMINAL
     *
     * @mbggenerated
     */
    private String terminal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usercore_user_register.INTEGRAL_LEVEL
     *
     * @mbggenerated
     */
    private String integralLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usercore_user_register.ACCOUNT_CHECK_STATUS
     *
     * @mbggenerated
     */
    private String accountCheckStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usercore_user_register.ACCOUNT_DATE
     *
     * @mbggenerated
     */
    private Date accountDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usercore_user_register.UPDATE_MOBLIE_STATUS
     *
     * @mbggenerated
     */
    private String updateMoblieStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usercore_user_register.IS_BLACK_LIST
     *
     * @mbggenerated
     */
    private String isBlackList;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usercore_user_register.PASSWORD
     *
     * @return the value of usercore_user_register.PASSWORD
     *
     * @mbggenerated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usercore_user_register.PASSWORD
     *
     * @param password the value for usercore_user_register.PASSWORD
     *
     * @mbggenerated
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usercore_user_register.NICK
     *
     * @return the value of usercore_user_register.NICK
     *
     * @mbggenerated
     */
    public String getNick() {
        return nick;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usercore_user_register.NICK
     *
     * @param nick the value for usercore_user_register.NICK
     *
     * @mbggenerated
     */
    public void setNick(String nick) {
        this.nick = nick;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usercore_user_register.USER_TYPE
     *
     * @return the value of usercore_user_register.USER_TYPE
     *
     * @mbggenerated
     */
    public String getUserType() {
        return userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usercore_user_register.USER_TYPE
     *
     * @param userType the value for usercore_user_register.USER_TYPE
     *
     * @mbggenerated
     */
    public void setUserType(String userType) {
        this.userType = userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usercore_user_register.IF_BINDCARD
     *
     * @return the value of usercore_user_register.IF_BINDCARD
     *
     * @mbggenerated
     */
    public String getIfBindcard() {
        return ifBindcard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usercore_user_register.IF_BINDCARD
     *
     * @param ifBindcard the value for usercore_user_register.IF_BINDCARD
     *
     * @mbggenerated
     */
    public void setIfBindcard(String ifBindcard) {
        this.ifBindcard = ifBindcard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usercore_user_register.IF_REALNAME
     *
     * @return the value of usercore_user_register.IF_REALNAME
     *
     * @mbggenerated
     */
    public String getIfRealname() {
        return ifRealname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usercore_user_register.IF_REALNAME
     *
     * @param ifRealname the value for usercore_user_register.IF_REALNAME
     *
     * @mbggenerated
     */
    public void setIfRealname(String ifRealname) {
        this.ifRealname = ifRealname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usercore_user_register.IF_ACCOUNT
     *
     * @return the value of usercore_user_register.IF_ACCOUNT
     *
     * @mbggenerated
     */
    public String getIfAccount() {
        return ifAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usercore_user_register.IF_ACCOUNT
     *
     * @param ifAccount the value for usercore_user_register.IF_ACCOUNT
     *
     * @mbggenerated
     */
    public void setIfAccount(String ifAccount) {
        this.ifAccount = ifAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usercore_user_register.IF_FIRSTBUY
     *
     * @return the value of usercore_user_register.IF_FIRSTBUY
     *
     * @mbggenerated
     */
    public String getIfFirstbuy() {
        return ifFirstbuy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usercore_user_register.IF_FIRSTBUY
     *
     * @param ifFirstbuy the value for usercore_user_register.IF_FIRSTBUY
     *
     * @mbggenerated
     */
    public void setIfFirstbuy(String ifFirstbuy) {
        this.ifFirstbuy = ifFirstbuy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usercore_user_register.IF_PAYPWD
     *
     * @return the value of usercore_user_register.IF_PAYPWD
     *
     * @mbggenerated
     */
    public String getIfPaypwd() {
        return ifPaypwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usercore_user_register.IF_PAYPWD
     *
     * @param ifPaypwd the value for usercore_user_register.IF_PAYPWD
     *
     * @mbggenerated
     */
    public void setIfPaypwd(String ifPaypwd) {
        this.ifPaypwd = ifPaypwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usercore_user_register.SEC_LEVEL
     *
     * @return the value of usercore_user_register.SEC_LEVEL
     *
     * @mbggenerated
     */
    public String getSecLevel() {
        return secLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usercore_user_register.SEC_LEVEL
     *
     * @param secLevel the value for usercore_user_register.SEC_LEVEL
     *
     * @mbggenerated
     */
    public void setSecLevel(String secLevel) {
        this.secLevel = secLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usercore_user_register.USER_LEVEL
     *
     * @return the value of usercore_user_register.USER_LEVEL
     *
     * @mbggenerated
     */
    public String getUserLevel() {
        return userLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usercore_user_register.USER_LEVEL
     *
     * @param userLevel the value for usercore_user_register.USER_LEVEL
     *
     * @mbggenerated
     */
    public void setUserLevel(String userLevel) {
        this.userLevel = userLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usercore_user_register.STATUS
     *
     * @return the value of usercore_user_register.STATUS
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usercore_user_register.STATUS
     *
     * @param status the value for usercore_user_register.STATUS
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usercore_user_register.CREATE_TIME
     *
     * @return the value of usercore_user_register.CREATE_TIME
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usercore_user_register.CREATE_TIME
     *
     * @param createTime the value for usercore_user_register.CREATE_TIME
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usercore_user_register.UPDATE_TIME
     *
     * @return the value of usercore_user_register.UPDATE_TIME
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usercore_user_register.UPDATE_TIME
     *
     * @param updateTime the value for usercore_user_register.UPDATE_TIME
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usercore_user_register.OPERATOR
     *
     * @return the value of usercore_user_register.OPERATOR
     *
     * @mbggenerated
     */
    public String getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usercore_user_register.OPERATOR
     *
     * @param operator the value for usercore_user_register.OPERATOR
     *
     * @mbggenerated
     */
    public void setOperator(String operator) {
        this.operator = operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usercore_user_register.REFEREE
     *
     * @return the value of usercore_user_register.REFEREE
     *
     * @mbggenerated
     */
    public String getReferee() {
        return referee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usercore_user_register.REFEREE
     *
     * @param referee the value for usercore_user_register.REFEREE
     *
     * @mbggenerated
     */
    public void setReferee(String referee) {
        this.referee = referee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usercore_user_register.LOGO
     *
     * @return the value of usercore_user_register.LOGO
     *
     * @mbggenerated
     */
    public String getLogo() {
        return logo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usercore_user_register.LOGO
     *
     * @param logo the value for usercore_user_register.LOGO
     *
     * @mbggenerated
     */
    public void setLogo(String logo) {
        this.logo = logo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usercore_user_register.CHANNEL_NUM
     *
     * @return the value of usercore_user_register.CHANNEL_NUM
     *
     * @mbggenerated
     */
    public String getChannelNum() {
        return channelNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usercore_user_register.CHANNEL_NUM
     *
     * @param channelNum the value for usercore_user_register.CHANNEL_NUM
     *
     * @mbggenerated
     */
    public void setChannelNum(String channelNum) {
        this.channelNum = channelNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usercore_user_register.TERMINAL
     *
     * @return the value of usercore_user_register.TERMINAL
     *
     * @mbggenerated
     */
    public String getTerminal() {
        return terminal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usercore_user_register.TERMINAL
     *
     * @param terminal the value for usercore_user_register.TERMINAL
     *
     * @mbggenerated
     */
    public void setTerminal(String terminal) {
        this.terminal = terminal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usercore_user_register.INTEGRAL_LEVEL
     *
     * @return the value of usercore_user_register.INTEGRAL_LEVEL
     *
     * @mbggenerated
     */
    public String getIntegralLevel() {
        return integralLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usercore_user_register.INTEGRAL_LEVEL
     *
     * @param integralLevel the value for usercore_user_register.INTEGRAL_LEVEL
     *
     * @mbggenerated
     */
    public void setIntegralLevel(String integralLevel) {
        this.integralLevel = integralLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usercore_user_register.ACCOUNT_CHECK_STATUS
     *
     * @return the value of usercore_user_register.ACCOUNT_CHECK_STATUS
     *
     * @mbggenerated
     */
    public String getAccountCheckStatus() {
        return accountCheckStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usercore_user_register.ACCOUNT_CHECK_STATUS
     *
     * @param accountCheckStatus the value for usercore_user_register.ACCOUNT_CHECK_STATUS
     *
     * @mbggenerated
     */
    public void setAccountCheckStatus(String accountCheckStatus) {
        this.accountCheckStatus = accountCheckStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usercore_user_register.ACCOUNT_DATE
     *
     * @return the value of usercore_user_register.ACCOUNT_DATE
     *
     * @mbggenerated
     */
    public Date getAccountDate() {
        return accountDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usercore_user_register.ACCOUNT_DATE
     *
     * @param accountDate the value for usercore_user_register.ACCOUNT_DATE
     *
     * @mbggenerated
     */
    public void setAccountDate(Date accountDate) {
        this.accountDate = accountDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usercore_user_register.UPDATE_MOBLIE_STATUS
     *
     * @return the value of usercore_user_register.UPDATE_MOBLIE_STATUS
     *
     * @mbggenerated
     */
    public String getUpdateMoblieStatus() {
        return updateMoblieStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usercore_user_register.UPDATE_MOBLIE_STATUS
     *
     * @param updateMoblieStatus the value for usercore_user_register.UPDATE_MOBLIE_STATUS
     *
     * @mbggenerated
     */
    public void setUpdateMoblieStatus(String updateMoblieStatus) {
        this.updateMoblieStatus = updateMoblieStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usercore_user_register.IS_BLACK_LIST
     *
     * @return the value of usercore_user_register.IS_BLACK_LIST
     *
     * @mbggenerated
     */
    public String getIsBlackList() {
        return isBlackList;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usercore_user_register.IS_BLACK_LIST
     *
     * @param isBlackList the value for usercore_user_register.IS_BLACK_LIST
     *
     * @mbggenerated
     */
    public void setIsBlackList(String isBlackList) {
        this.isBlackList = isBlackList;
    }
}