package com.example.demo.bean;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class UsercoreUserRegisterExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table usercore_user_register
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table usercore_user_register
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table usercore_user_register
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usercore_user_register
     *
     * @mbggenerated
     */
    public UsercoreUserRegisterExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usercore_user_register
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usercore_user_register
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usercore_user_register
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usercore_user_register
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usercore_user_register
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usercore_user_register
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usercore_user_register
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usercore_user_register
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usercore_user_register
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usercore_user_register
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table usercore_user_register
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andTenantIdIsNull() {
            addCriterion("TENANT_ID is null");
            return (Criteria) this;
        }

        public Criteria andTenantIdIsNotNull() {
            addCriterion("TENANT_ID is not null");
            return (Criteria) this;
        }

        public Criteria andTenantIdEqualTo(String value) {
            addCriterion("TENANT_ID =", value, "tenantId");
            return (Criteria) this;
        }

        public Criteria andTenantIdNotEqualTo(String value) {
            addCriterion("TENANT_ID <>", value, "tenantId");
            return (Criteria) this;
        }

        public Criteria andTenantIdGreaterThan(String value) {
            addCriterion("TENANT_ID >", value, "tenantId");
            return (Criteria) this;
        }

        public Criteria andTenantIdGreaterThanOrEqualTo(String value) {
            addCriterion("TENANT_ID >=", value, "tenantId");
            return (Criteria) this;
        }

        public Criteria andTenantIdLessThan(String value) {
            addCriterion("TENANT_ID <", value, "tenantId");
            return (Criteria) this;
        }

        public Criteria andTenantIdLessThanOrEqualTo(String value) {
            addCriterion("TENANT_ID <=", value, "tenantId");
            return (Criteria) this;
        }

        public Criteria andTenantIdLike(String value) {
            addCriterion("TENANT_ID like", value, "tenantId");
            return (Criteria) this;
        }

        public Criteria andTenantIdNotLike(String value) {
            addCriterion("TENANT_ID not like", value, "tenantId");
            return (Criteria) this;
        }

        public Criteria andTenantIdIn(List<String> values) {
            addCriterion("TENANT_ID in", values, "tenantId");
            return (Criteria) this;
        }

        public Criteria andTenantIdNotIn(List<String> values) {
            addCriterion("TENANT_ID not in", values, "tenantId");
            return (Criteria) this;
        }

        public Criteria andTenantIdBetween(String value1, String value2) {
            addCriterion("TENANT_ID between", value1, value2, "tenantId");
            return (Criteria) this;
        }

        public Criteria andTenantIdNotBetween(String value1, String value2) {
            addCriterion("TENANT_ID not between", value1, value2, "tenantId");
            return (Criteria) this;
        }

        public Criteria andUserNoIsNull() {
            addCriterion("USER_NO is null");
            return (Criteria) this;
        }

        public Criteria andUserNoIsNotNull() {
            addCriterion("USER_NO is not null");
            return (Criteria) this;
        }

        public Criteria andUserNoEqualTo(String value) {
            addCriterion("USER_NO =", value, "userNo");
            return (Criteria) this;
        }

        public Criteria andUserNoNotEqualTo(String value) {
            addCriterion("USER_NO <>", value, "userNo");
            return (Criteria) this;
        }

        public Criteria andUserNoGreaterThan(String value) {
            addCriterion("USER_NO >", value, "userNo");
            return (Criteria) this;
        }

        public Criteria andUserNoGreaterThanOrEqualTo(String value) {
            addCriterion("USER_NO >=", value, "userNo");
            return (Criteria) this;
        }

        public Criteria andUserNoLessThan(String value) {
            addCriterion("USER_NO <", value, "userNo");
            return (Criteria) this;
        }

        public Criteria andUserNoLessThanOrEqualTo(String value) {
            addCriterion("USER_NO <=", value, "userNo");
            return (Criteria) this;
        }

        public Criteria andUserNoLike(String value) {
            addCriterion("USER_NO like", value, "userNo");
            return (Criteria) this;
        }

        public Criteria andUserNoNotLike(String value) {
            addCriterion("USER_NO not like", value, "userNo");
            return (Criteria) this;
        }

        public Criteria andUserNoIn(List<String> values) {
            addCriterion("USER_NO in", values, "userNo");
            return (Criteria) this;
        }

        public Criteria andUserNoNotIn(List<String> values) {
            addCriterion("USER_NO not in", values, "userNo");
            return (Criteria) this;
        }

        public Criteria andUserNoBetween(String value1, String value2) {
            addCriterion("USER_NO between", value1, value2, "userNo");
            return (Criteria) this;
        }

        public Criteria andUserNoNotBetween(String value1, String value2) {
            addCriterion("USER_NO not between", value1, value2, "userNo");
            return (Criteria) this;
        }

        public Criteria andPasswordIsNull() {
            addCriterion("PASSWORD is null");
            return (Criteria) this;
        }

        public Criteria andPasswordIsNotNull() {
            addCriterion("PASSWORD is not null");
            return (Criteria) this;
        }

        public Criteria andPasswordEqualTo(String value) {
            addCriterion("PASSWORD =", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotEqualTo(String value) {
            addCriterion("PASSWORD <>", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordGreaterThan(String value) {
            addCriterion("PASSWORD >", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordGreaterThanOrEqualTo(String value) {
            addCriterion("PASSWORD >=", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordLessThan(String value) {
            addCriterion("PASSWORD <", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordLessThanOrEqualTo(String value) {
            addCriterion("PASSWORD <=", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordLike(String value) {
            addCriterion("PASSWORD like", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotLike(String value) {
            addCriterion("PASSWORD not like", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordIn(List<String> values) {
            addCriterion("PASSWORD in", values, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotIn(List<String> values) {
            addCriterion("PASSWORD not in", values, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordBetween(String value1, String value2) {
            addCriterion("PASSWORD between", value1, value2, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotBetween(String value1, String value2) {
            addCriterion("PASSWORD not between", value1, value2, "password");
            return (Criteria) this;
        }

        public Criteria andNickIsNull() {
            addCriterion("NICK is null");
            return (Criteria) this;
        }

        public Criteria andNickIsNotNull() {
            addCriterion("NICK is not null");
            return (Criteria) this;
        }

        public Criteria andNickEqualTo(String value) {
            addCriterion("NICK =", value, "nick");
            return (Criteria) this;
        }

        public Criteria andNickNotEqualTo(String value) {
            addCriterion("NICK <>", value, "nick");
            return (Criteria) this;
        }

        public Criteria andNickGreaterThan(String value) {
            addCriterion("NICK >", value, "nick");
            return (Criteria) this;
        }

        public Criteria andNickGreaterThanOrEqualTo(String value) {
            addCriterion("NICK >=", value, "nick");
            return (Criteria) this;
        }

        public Criteria andNickLessThan(String value) {
            addCriterion("NICK <", value, "nick");
            return (Criteria) this;
        }

        public Criteria andNickLessThanOrEqualTo(String value) {
            addCriterion("NICK <=", value, "nick");
            return (Criteria) this;
        }

        public Criteria andNickLike(String value) {
            addCriterion("NICK like", value, "nick");
            return (Criteria) this;
        }

        public Criteria andNickNotLike(String value) {
            addCriterion("NICK not like", value, "nick");
            return (Criteria) this;
        }

        public Criteria andNickIn(List<String> values) {
            addCriterion("NICK in", values, "nick");
            return (Criteria) this;
        }

        public Criteria andNickNotIn(List<String> values) {
            addCriterion("NICK not in", values, "nick");
            return (Criteria) this;
        }

        public Criteria andNickBetween(String value1, String value2) {
            addCriterion("NICK between", value1, value2, "nick");
            return (Criteria) this;
        }

        public Criteria andNickNotBetween(String value1, String value2) {
            addCriterion("NICK not between", value1, value2, "nick");
            return (Criteria) this;
        }

        public Criteria andUserTypeIsNull() {
            addCriterion("USER_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andUserTypeIsNotNull() {
            addCriterion("USER_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andUserTypeEqualTo(String value) {
            addCriterion("USER_TYPE =", value, "userType");
            return (Criteria) this;
        }

        public Criteria andUserTypeNotEqualTo(String value) {
            addCriterion("USER_TYPE <>", value, "userType");
            return (Criteria) this;
        }

        public Criteria andUserTypeGreaterThan(String value) {
            addCriterion("USER_TYPE >", value, "userType");
            return (Criteria) this;
        }

        public Criteria andUserTypeGreaterThanOrEqualTo(String value) {
            addCriterion("USER_TYPE >=", value, "userType");
            return (Criteria) this;
        }

        public Criteria andUserTypeLessThan(String value) {
            addCriterion("USER_TYPE <", value, "userType");
            return (Criteria) this;
        }

        public Criteria andUserTypeLessThanOrEqualTo(String value) {
            addCriterion("USER_TYPE <=", value, "userType");
            return (Criteria) this;
        }

        public Criteria andUserTypeLike(String value) {
            addCriterion("USER_TYPE like", value, "userType");
            return (Criteria) this;
        }

        public Criteria andUserTypeNotLike(String value) {
            addCriterion("USER_TYPE not like", value, "userType");
            return (Criteria) this;
        }

        public Criteria andUserTypeIn(List<String> values) {
            addCriterion("USER_TYPE in", values, "userType");
            return (Criteria) this;
        }

        public Criteria andUserTypeNotIn(List<String> values) {
            addCriterion("USER_TYPE not in", values, "userType");
            return (Criteria) this;
        }

        public Criteria andUserTypeBetween(String value1, String value2) {
            addCriterion("USER_TYPE between", value1, value2, "userType");
            return (Criteria) this;
        }

        public Criteria andUserTypeNotBetween(String value1, String value2) {
            addCriterion("USER_TYPE not between", value1, value2, "userType");
            return (Criteria) this;
        }

        public Criteria andIfBindcardIsNull() {
            addCriterion("IF_BINDCARD is null");
            return (Criteria) this;
        }

        public Criteria andIfBindcardIsNotNull() {
            addCriterion("IF_BINDCARD is not null");
            return (Criteria) this;
        }

        public Criteria andIfBindcardEqualTo(String value) {
            addCriterion("IF_BINDCARD =", value, "ifBindcard");
            return (Criteria) this;
        }

        public Criteria andIfBindcardNotEqualTo(String value) {
            addCriterion("IF_BINDCARD <>", value, "ifBindcard");
            return (Criteria) this;
        }

        public Criteria andIfBindcardGreaterThan(String value) {
            addCriterion("IF_BINDCARD >", value, "ifBindcard");
            return (Criteria) this;
        }

        public Criteria andIfBindcardGreaterThanOrEqualTo(String value) {
            addCriterion("IF_BINDCARD >=", value, "ifBindcard");
            return (Criteria) this;
        }

        public Criteria andIfBindcardLessThan(String value) {
            addCriterion("IF_BINDCARD <", value, "ifBindcard");
            return (Criteria) this;
        }

        public Criteria andIfBindcardLessThanOrEqualTo(String value) {
            addCriterion("IF_BINDCARD <=", value, "ifBindcard");
            return (Criteria) this;
        }

        public Criteria andIfBindcardLike(String value) {
            addCriterion("IF_BINDCARD like", value, "ifBindcard");
            return (Criteria) this;
        }

        public Criteria andIfBindcardNotLike(String value) {
            addCriterion("IF_BINDCARD not like", value, "ifBindcard");
            return (Criteria) this;
        }

        public Criteria andIfBindcardIn(List<String> values) {
            addCriterion("IF_BINDCARD in", values, "ifBindcard");
            return (Criteria) this;
        }

        public Criteria andIfBindcardNotIn(List<String> values) {
            addCriterion("IF_BINDCARD not in", values, "ifBindcard");
            return (Criteria) this;
        }

        public Criteria andIfBindcardBetween(String value1, String value2) {
            addCriterion("IF_BINDCARD between", value1, value2, "ifBindcard");
            return (Criteria) this;
        }

        public Criteria andIfBindcardNotBetween(String value1, String value2) {
            addCriterion("IF_BINDCARD not between", value1, value2, "ifBindcard");
            return (Criteria) this;
        }

        public Criteria andIfRealnameIsNull() {
            addCriterion("IF_REALNAME is null");
            return (Criteria) this;
        }

        public Criteria andIfRealnameIsNotNull() {
            addCriterion("IF_REALNAME is not null");
            return (Criteria) this;
        }

        public Criteria andIfRealnameEqualTo(String value) {
            addCriterion("IF_REALNAME =", value, "ifRealname");
            return (Criteria) this;
        }

        public Criteria andIfRealnameNotEqualTo(String value) {
            addCriterion("IF_REALNAME <>", value, "ifRealname");
            return (Criteria) this;
        }

        public Criteria andIfRealnameGreaterThan(String value) {
            addCriterion("IF_REALNAME >", value, "ifRealname");
            return (Criteria) this;
        }

        public Criteria andIfRealnameGreaterThanOrEqualTo(String value) {
            addCriterion("IF_REALNAME >=", value, "ifRealname");
            return (Criteria) this;
        }

        public Criteria andIfRealnameLessThan(String value) {
            addCriterion("IF_REALNAME <", value, "ifRealname");
            return (Criteria) this;
        }

        public Criteria andIfRealnameLessThanOrEqualTo(String value) {
            addCriterion("IF_REALNAME <=", value, "ifRealname");
            return (Criteria) this;
        }

        public Criteria andIfRealnameLike(String value) {
            addCriterion("IF_REALNAME like", value, "ifRealname");
            return (Criteria) this;
        }

        public Criteria andIfRealnameNotLike(String value) {
            addCriterion("IF_REALNAME not like", value, "ifRealname");
            return (Criteria) this;
        }

        public Criteria andIfRealnameIn(List<String> values) {
            addCriterion("IF_REALNAME in", values, "ifRealname");
            return (Criteria) this;
        }

        public Criteria andIfRealnameNotIn(List<String> values) {
            addCriterion("IF_REALNAME not in", values, "ifRealname");
            return (Criteria) this;
        }

        public Criteria andIfRealnameBetween(String value1, String value2) {
            addCriterion("IF_REALNAME between", value1, value2, "ifRealname");
            return (Criteria) this;
        }

        public Criteria andIfRealnameNotBetween(String value1, String value2) {
            addCriterion("IF_REALNAME not between", value1, value2, "ifRealname");
            return (Criteria) this;
        }

        public Criteria andIfAccountIsNull() {
            addCriterion("IF_ACCOUNT is null");
            return (Criteria) this;
        }

        public Criteria andIfAccountIsNotNull() {
            addCriterion("IF_ACCOUNT is not null");
            return (Criteria) this;
        }

        public Criteria andIfAccountEqualTo(String value) {
            addCriterion("IF_ACCOUNT =", value, "ifAccount");
            return (Criteria) this;
        }

        public Criteria andIfAccountNotEqualTo(String value) {
            addCriterion("IF_ACCOUNT <>", value, "ifAccount");
            return (Criteria) this;
        }

        public Criteria andIfAccountGreaterThan(String value) {
            addCriterion("IF_ACCOUNT >", value, "ifAccount");
            return (Criteria) this;
        }

        public Criteria andIfAccountGreaterThanOrEqualTo(String value) {
            addCriterion("IF_ACCOUNT >=", value, "ifAccount");
            return (Criteria) this;
        }

        public Criteria andIfAccountLessThan(String value) {
            addCriterion("IF_ACCOUNT <", value, "ifAccount");
            return (Criteria) this;
        }

        public Criteria andIfAccountLessThanOrEqualTo(String value) {
            addCriterion("IF_ACCOUNT <=", value, "ifAccount");
            return (Criteria) this;
        }

        public Criteria andIfAccountLike(String value) {
            addCriterion("IF_ACCOUNT like", value, "ifAccount");
            return (Criteria) this;
        }

        public Criteria andIfAccountNotLike(String value) {
            addCriterion("IF_ACCOUNT not like", value, "ifAccount");
            return (Criteria) this;
        }

        public Criteria andIfAccountIn(List<String> values) {
            addCriterion("IF_ACCOUNT in", values, "ifAccount");
            return (Criteria) this;
        }

        public Criteria andIfAccountNotIn(List<String> values) {
            addCriterion("IF_ACCOUNT not in", values, "ifAccount");
            return (Criteria) this;
        }

        public Criteria andIfAccountBetween(String value1, String value2) {
            addCriterion("IF_ACCOUNT between", value1, value2, "ifAccount");
            return (Criteria) this;
        }

        public Criteria andIfAccountNotBetween(String value1, String value2) {
            addCriterion("IF_ACCOUNT not between", value1, value2, "ifAccount");
            return (Criteria) this;
        }

        public Criteria andIfFirstbuyIsNull() {
            addCriterion("IF_FIRSTBUY is null");
            return (Criteria) this;
        }

        public Criteria andIfFirstbuyIsNotNull() {
            addCriterion("IF_FIRSTBUY is not null");
            return (Criteria) this;
        }

        public Criteria andIfFirstbuyEqualTo(String value) {
            addCriterion("IF_FIRSTBUY =", value, "ifFirstbuy");
            return (Criteria) this;
        }

        public Criteria andIfFirstbuyNotEqualTo(String value) {
            addCriterion("IF_FIRSTBUY <>", value, "ifFirstbuy");
            return (Criteria) this;
        }

        public Criteria andIfFirstbuyGreaterThan(String value) {
            addCriterion("IF_FIRSTBUY >", value, "ifFirstbuy");
            return (Criteria) this;
        }

        public Criteria andIfFirstbuyGreaterThanOrEqualTo(String value) {
            addCriterion("IF_FIRSTBUY >=", value, "ifFirstbuy");
            return (Criteria) this;
        }

        public Criteria andIfFirstbuyLessThan(String value) {
            addCriterion("IF_FIRSTBUY <", value, "ifFirstbuy");
            return (Criteria) this;
        }

        public Criteria andIfFirstbuyLessThanOrEqualTo(String value) {
            addCriterion("IF_FIRSTBUY <=", value, "ifFirstbuy");
            return (Criteria) this;
        }

        public Criteria andIfFirstbuyLike(String value) {
            addCriterion("IF_FIRSTBUY like", value, "ifFirstbuy");
            return (Criteria) this;
        }

        public Criteria andIfFirstbuyNotLike(String value) {
            addCriterion("IF_FIRSTBUY not like", value, "ifFirstbuy");
            return (Criteria) this;
        }

        public Criteria andIfFirstbuyIn(List<String> values) {
            addCriterion("IF_FIRSTBUY in", values, "ifFirstbuy");
            return (Criteria) this;
        }

        public Criteria andIfFirstbuyNotIn(List<String> values) {
            addCriterion("IF_FIRSTBUY not in", values, "ifFirstbuy");
            return (Criteria) this;
        }

        public Criteria andIfFirstbuyBetween(String value1, String value2) {
            addCriterion("IF_FIRSTBUY between", value1, value2, "ifFirstbuy");
            return (Criteria) this;
        }

        public Criteria andIfFirstbuyNotBetween(String value1, String value2) {
            addCriterion("IF_FIRSTBUY not between", value1, value2, "ifFirstbuy");
            return (Criteria) this;
        }

        public Criteria andIfPaypwdIsNull() {
            addCriterion("IF_PAYPWD is null");
            return (Criteria) this;
        }

        public Criteria andIfPaypwdIsNotNull() {
            addCriterion("IF_PAYPWD is not null");
            return (Criteria) this;
        }

        public Criteria andIfPaypwdEqualTo(String value) {
            addCriterion("IF_PAYPWD =", value, "ifPaypwd");
            return (Criteria) this;
        }

        public Criteria andIfPaypwdNotEqualTo(String value) {
            addCriterion("IF_PAYPWD <>", value, "ifPaypwd");
            return (Criteria) this;
        }

        public Criteria andIfPaypwdGreaterThan(String value) {
            addCriterion("IF_PAYPWD >", value, "ifPaypwd");
            return (Criteria) this;
        }

        public Criteria andIfPaypwdGreaterThanOrEqualTo(String value) {
            addCriterion("IF_PAYPWD >=", value, "ifPaypwd");
            return (Criteria) this;
        }

        public Criteria andIfPaypwdLessThan(String value) {
            addCriterion("IF_PAYPWD <", value, "ifPaypwd");
            return (Criteria) this;
        }

        public Criteria andIfPaypwdLessThanOrEqualTo(String value) {
            addCriterion("IF_PAYPWD <=", value, "ifPaypwd");
            return (Criteria) this;
        }

        public Criteria andIfPaypwdLike(String value) {
            addCriterion("IF_PAYPWD like", value, "ifPaypwd");
            return (Criteria) this;
        }

        public Criteria andIfPaypwdNotLike(String value) {
            addCriterion("IF_PAYPWD not like", value, "ifPaypwd");
            return (Criteria) this;
        }

        public Criteria andIfPaypwdIn(List<String> values) {
            addCriterion("IF_PAYPWD in", values, "ifPaypwd");
            return (Criteria) this;
        }

        public Criteria andIfPaypwdNotIn(List<String> values) {
            addCriterion("IF_PAYPWD not in", values, "ifPaypwd");
            return (Criteria) this;
        }

        public Criteria andIfPaypwdBetween(String value1, String value2) {
            addCriterion("IF_PAYPWD between", value1, value2, "ifPaypwd");
            return (Criteria) this;
        }

        public Criteria andIfPaypwdNotBetween(String value1, String value2) {
            addCriterion("IF_PAYPWD not between", value1, value2, "ifPaypwd");
            return (Criteria) this;
        }

        public Criteria andSecLevelIsNull() {
            addCriterion("SEC_LEVEL is null");
            return (Criteria) this;
        }

        public Criteria andSecLevelIsNotNull() {
            addCriterion("SEC_LEVEL is not null");
            return (Criteria) this;
        }

        public Criteria andSecLevelEqualTo(String value) {
            addCriterion("SEC_LEVEL =", value, "secLevel");
            return (Criteria) this;
        }

        public Criteria andSecLevelNotEqualTo(String value) {
            addCriterion("SEC_LEVEL <>", value, "secLevel");
            return (Criteria) this;
        }

        public Criteria andSecLevelGreaterThan(String value) {
            addCriterion("SEC_LEVEL >", value, "secLevel");
            return (Criteria) this;
        }

        public Criteria andSecLevelGreaterThanOrEqualTo(String value) {
            addCriterion("SEC_LEVEL >=", value, "secLevel");
            return (Criteria) this;
        }

        public Criteria andSecLevelLessThan(String value) {
            addCriterion("SEC_LEVEL <", value, "secLevel");
            return (Criteria) this;
        }

        public Criteria andSecLevelLessThanOrEqualTo(String value) {
            addCriterion("SEC_LEVEL <=", value, "secLevel");
            return (Criteria) this;
        }

        public Criteria andSecLevelLike(String value) {
            addCriterion("SEC_LEVEL like", value, "secLevel");
            return (Criteria) this;
        }

        public Criteria andSecLevelNotLike(String value) {
            addCriterion("SEC_LEVEL not like", value, "secLevel");
            return (Criteria) this;
        }

        public Criteria andSecLevelIn(List<String> values) {
            addCriterion("SEC_LEVEL in", values, "secLevel");
            return (Criteria) this;
        }

        public Criteria andSecLevelNotIn(List<String> values) {
            addCriterion("SEC_LEVEL not in", values, "secLevel");
            return (Criteria) this;
        }

        public Criteria andSecLevelBetween(String value1, String value2) {
            addCriterion("SEC_LEVEL between", value1, value2, "secLevel");
            return (Criteria) this;
        }

        public Criteria andSecLevelNotBetween(String value1, String value2) {
            addCriterion("SEC_LEVEL not between", value1, value2, "secLevel");
            return (Criteria) this;
        }

        public Criteria andUserLevelIsNull() {
            addCriterion("USER_LEVEL is null");
            return (Criteria) this;
        }

        public Criteria andUserLevelIsNotNull() {
            addCriterion("USER_LEVEL is not null");
            return (Criteria) this;
        }

        public Criteria andUserLevelEqualTo(String value) {
            addCriterion("USER_LEVEL =", value, "userLevel");
            return (Criteria) this;
        }

        public Criteria andUserLevelNotEqualTo(String value) {
            addCriterion("USER_LEVEL <>", value, "userLevel");
            return (Criteria) this;
        }

        public Criteria andUserLevelGreaterThan(String value) {
            addCriterion("USER_LEVEL >", value, "userLevel");
            return (Criteria) this;
        }

        public Criteria andUserLevelGreaterThanOrEqualTo(String value) {
            addCriterion("USER_LEVEL >=", value, "userLevel");
            return (Criteria) this;
        }

        public Criteria andUserLevelLessThan(String value) {
            addCriterion("USER_LEVEL <", value, "userLevel");
            return (Criteria) this;
        }

        public Criteria andUserLevelLessThanOrEqualTo(String value) {
            addCriterion("USER_LEVEL <=", value, "userLevel");
            return (Criteria) this;
        }

        public Criteria andUserLevelLike(String value) {
            addCriterion("USER_LEVEL like", value, "userLevel");
            return (Criteria) this;
        }

        public Criteria andUserLevelNotLike(String value) {
            addCriterion("USER_LEVEL not like", value, "userLevel");
            return (Criteria) this;
        }

        public Criteria andUserLevelIn(List<String> values) {
            addCriterion("USER_LEVEL in", values, "userLevel");
            return (Criteria) this;
        }

        public Criteria andUserLevelNotIn(List<String> values) {
            addCriterion("USER_LEVEL not in", values, "userLevel");
            return (Criteria) this;
        }

        public Criteria andUserLevelBetween(String value1, String value2) {
            addCriterion("USER_LEVEL between", value1, value2, "userLevel");
            return (Criteria) this;
        }

        public Criteria andUserLevelNotBetween(String value1, String value2) {
            addCriterion("USER_LEVEL not between", value1, value2, "userLevel");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("STATUS is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("STATUS is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(String value) {
            addCriterion("STATUS =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(String value) {
            addCriterion("STATUS <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(String value) {
            addCriterion("STATUS >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(String value) {
            addCriterion("STATUS >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(String value) {
            addCriterion("STATUS <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(String value) {
            addCriterion("STATUS <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLike(String value) {
            addCriterion("STATUS like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotLike(String value) {
            addCriterion("STATUS not like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<String> values) {
            addCriterion("STATUS in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<String> values) {
            addCriterion("STATUS not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(String value1, String value2) {
            addCriterion("STATUS between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(String value1, String value2) {
            addCriterion("STATUS not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("CREATE_TIME is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("CREATE_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("CREATE_TIME =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("CREATE_TIME <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("CREATE_TIME >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("CREATE_TIME >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("CREATE_TIME <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("CREATE_TIME <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("CREATE_TIME in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("CREATE_TIME not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("CREATE_TIME between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("CREATE_TIME not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("UPDATE_TIME is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("UPDATE_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("UPDATE_TIME =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("UPDATE_TIME <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("UPDATE_TIME >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("UPDATE_TIME >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("UPDATE_TIME <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("UPDATE_TIME <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("UPDATE_TIME in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("UPDATE_TIME not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("UPDATE_TIME between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("UPDATE_TIME not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andOperatorIsNull() {
            addCriterion("OPERATOR is null");
            return (Criteria) this;
        }

        public Criteria andOperatorIsNotNull() {
            addCriterion("OPERATOR is not null");
            return (Criteria) this;
        }

        public Criteria andOperatorEqualTo(String value) {
            addCriterion("OPERATOR =", value, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorNotEqualTo(String value) {
            addCriterion("OPERATOR <>", value, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorGreaterThan(String value) {
            addCriterion("OPERATOR >", value, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorGreaterThanOrEqualTo(String value) {
            addCriterion("OPERATOR >=", value, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorLessThan(String value) {
            addCriterion("OPERATOR <", value, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorLessThanOrEqualTo(String value) {
            addCriterion("OPERATOR <=", value, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorLike(String value) {
            addCriterion("OPERATOR like", value, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorNotLike(String value) {
            addCriterion("OPERATOR not like", value, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorIn(List<String> values) {
            addCriterion("OPERATOR in", values, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorNotIn(List<String> values) {
            addCriterion("OPERATOR not in", values, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorBetween(String value1, String value2) {
            addCriterion("OPERATOR between", value1, value2, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorNotBetween(String value1, String value2) {
            addCriterion("OPERATOR not between", value1, value2, "operator");
            return (Criteria) this;
        }

        public Criteria andRefereeIsNull() {
            addCriterion("REFEREE is null");
            return (Criteria) this;
        }

        public Criteria andRefereeIsNotNull() {
            addCriterion("REFEREE is not null");
            return (Criteria) this;
        }

        public Criteria andRefereeEqualTo(String value) {
            addCriterion("REFEREE =", value, "referee");
            return (Criteria) this;
        }

        public Criteria andRefereeNotEqualTo(String value) {
            addCriterion("REFEREE <>", value, "referee");
            return (Criteria) this;
        }

        public Criteria andRefereeGreaterThan(String value) {
            addCriterion("REFEREE >", value, "referee");
            return (Criteria) this;
        }

        public Criteria andRefereeGreaterThanOrEqualTo(String value) {
            addCriterion("REFEREE >=", value, "referee");
            return (Criteria) this;
        }

        public Criteria andRefereeLessThan(String value) {
            addCriterion("REFEREE <", value, "referee");
            return (Criteria) this;
        }

        public Criteria andRefereeLessThanOrEqualTo(String value) {
            addCriterion("REFEREE <=", value, "referee");
            return (Criteria) this;
        }

        public Criteria andRefereeLike(String value) {
            addCriterion("REFEREE like", value, "referee");
            return (Criteria) this;
        }

        public Criteria andRefereeNotLike(String value) {
            addCriterion("REFEREE not like", value, "referee");
            return (Criteria) this;
        }

        public Criteria andRefereeIn(List<String> values) {
            addCriterion("REFEREE in", values, "referee");
            return (Criteria) this;
        }

        public Criteria andRefereeNotIn(List<String> values) {
            addCriterion("REFEREE not in", values, "referee");
            return (Criteria) this;
        }

        public Criteria andRefereeBetween(String value1, String value2) {
            addCriterion("REFEREE between", value1, value2, "referee");
            return (Criteria) this;
        }

        public Criteria andRefereeNotBetween(String value1, String value2) {
            addCriterion("REFEREE not between", value1, value2, "referee");
            return (Criteria) this;
        }

        public Criteria andLogoIsNull() {
            addCriterion("LOGO is null");
            return (Criteria) this;
        }

        public Criteria andLogoIsNotNull() {
            addCriterion("LOGO is not null");
            return (Criteria) this;
        }

        public Criteria andLogoEqualTo(String value) {
            addCriterion("LOGO =", value, "logo");
            return (Criteria) this;
        }

        public Criteria andLogoNotEqualTo(String value) {
            addCriterion("LOGO <>", value, "logo");
            return (Criteria) this;
        }

        public Criteria andLogoGreaterThan(String value) {
            addCriterion("LOGO >", value, "logo");
            return (Criteria) this;
        }

        public Criteria andLogoGreaterThanOrEqualTo(String value) {
            addCriterion("LOGO >=", value, "logo");
            return (Criteria) this;
        }

        public Criteria andLogoLessThan(String value) {
            addCriterion("LOGO <", value, "logo");
            return (Criteria) this;
        }

        public Criteria andLogoLessThanOrEqualTo(String value) {
            addCriterion("LOGO <=", value, "logo");
            return (Criteria) this;
        }

        public Criteria andLogoLike(String value) {
            addCriterion("LOGO like", value, "logo");
            return (Criteria) this;
        }

        public Criteria andLogoNotLike(String value) {
            addCriterion("LOGO not like", value, "logo");
            return (Criteria) this;
        }

        public Criteria andLogoIn(List<String> values) {
            addCriterion("LOGO in", values, "logo");
            return (Criteria) this;
        }

        public Criteria andLogoNotIn(List<String> values) {
            addCriterion("LOGO not in", values, "logo");
            return (Criteria) this;
        }

        public Criteria andLogoBetween(String value1, String value2) {
            addCriterion("LOGO between", value1, value2, "logo");
            return (Criteria) this;
        }

        public Criteria andLogoNotBetween(String value1, String value2) {
            addCriterion("LOGO not between", value1, value2, "logo");
            return (Criteria) this;
        }

        public Criteria andChannelNumIsNull() {
            addCriterion("CHANNEL_NUM is null");
            return (Criteria) this;
        }

        public Criteria andChannelNumIsNotNull() {
            addCriterion("CHANNEL_NUM is not null");
            return (Criteria) this;
        }

        public Criteria andChannelNumEqualTo(String value) {
            addCriterion("CHANNEL_NUM =", value, "channelNum");
            return (Criteria) this;
        }

        public Criteria andChannelNumNotEqualTo(String value) {
            addCriterion("CHANNEL_NUM <>", value, "channelNum");
            return (Criteria) this;
        }

        public Criteria andChannelNumGreaterThan(String value) {
            addCriterion("CHANNEL_NUM >", value, "channelNum");
            return (Criteria) this;
        }

        public Criteria andChannelNumGreaterThanOrEqualTo(String value) {
            addCriterion("CHANNEL_NUM >=", value, "channelNum");
            return (Criteria) this;
        }

        public Criteria andChannelNumLessThan(String value) {
            addCriterion("CHANNEL_NUM <", value, "channelNum");
            return (Criteria) this;
        }

        public Criteria andChannelNumLessThanOrEqualTo(String value) {
            addCriterion("CHANNEL_NUM <=", value, "channelNum");
            return (Criteria) this;
        }

        public Criteria andChannelNumLike(String value) {
            addCriterion("CHANNEL_NUM like", value, "channelNum");
            return (Criteria) this;
        }

        public Criteria andChannelNumNotLike(String value) {
            addCriterion("CHANNEL_NUM not like", value, "channelNum");
            return (Criteria) this;
        }

        public Criteria andChannelNumIn(List<String> values) {
            addCriterion("CHANNEL_NUM in", values, "channelNum");
            return (Criteria) this;
        }

        public Criteria andChannelNumNotIn(List<String> values) {
            addCriterion("CHANNEL_NUM not in", values, "channelNum");
            return (Criteria) this;
        }

        public Criteria andChannelNumBetween(String value1, String value2) {
            addCriterion("CHANNEL_NUM between", value1, value2, "channelNum");
            return (Criteria) this;
        }

        public Criteria andChannelNumNotBetween(String value1, String value2) {
            addCriterion("CHANNEL_NUM not between", value1, value2, "channelNum");
            return (Criteria) this;
        }

        public Criteria andTerminalIsNull() {
            addCriterion("TERMINAL is null");
            return (Criteria) this;
        }

        public Criteria andTerminalIsNotNull() {
            addCriterion("TERMINAL is not null");
            return (Criteria) this;
        }

        public Criteria andTerminalEqualTo(String value) {
            addCriterion("TERMINAL =", value, "terminal");
            return (Criteria) this;
        }

        public Criteria andTerminalNotEqualTo(String value) {
            addCriterion("TERMINAL <>", value, "terminal");
            return (Criteria) this;
        }

        public Criteria andTerminalGreaterThan(String value) {
            addCriterion("TERMINAL >", value, "terminal");
            return (Criteria) this;
        }

        public Criteria andTerminalGreaterThanOrEqualTo(String value) {
            addCriterion("TERMINAL >=", value, "terminal");
            return (Criteria) this;
        }

        public Criteria andTerminalLessThan(String value) {
            addCriterion("TERMINAL <", value, "terminal");
            return (Criteria) this;
        }

        public Criteria andTerminalLessThanOrEqualTo(String value) {
            addCriterion("TERMINAL <=", value, "terminal");
            return (Criteria) this;
        }

        public Criteria andTerminalLike(String value) {
            addCriterion("TERMINAL like", value, "terminal");
            return (Criteria) this;
        }

        public Criteria andTerminalNotLike(String value) {
            addCriterion("TERMINAL not like", value, "terminal");
            return (Criteria) this;
        }

        public Criteria andTerminalIn(List<String> values) {
            addCriterion("TERMINAL in", values, "terminal");
            return (Criteria) this;
        }

        public Criteria andTerminalNotIn(List<String> values) {
            addCriterion("TERMINAL not in", values, "terminal");
            return (Criteria) this;
        }

        public Criteria andTerminalBetween(String value1, String value2) {
            addCriterion("TERMINAL between", value1, value2, "terminal");
            return (Criteria) this;
        }

        public Criteria andTerminalNotBetween(String value1, String value2) {
            addCriterion("TERMINAL not between", value1, value2, "terminal");
            return (Criteria) this;
        }

        public Criteria andIntegralLevelIsNull() {
            addCriterion("INTEGRAL_LEVEL is null");
            return (Criteria) this;
        }

        public Criteria andIntegralLevelIsNotNull() {
            addCriterion("INTEGRAL_LEVEL is not null");
            return (Criteria) this;
        }

        public Criteria andIntegralLevelEqualTo(String value) {
            addCriterion("INTEGRAL_LEVEL =", value, "integralLevel");
            return (Criteria) this;
        }

        public Criteria andIntegralLevelNotEqualTo(String value) {
            addCriterion("INTEGRAL_LEVEL <>", value, "integralLevel");
            return (Criteria) this;
        }

        public Criteria andIntegralLevelGreaterThan(String value) {
            addCriterion("INTEGRAL_LEVEL >", value, "integralLevel");
            return (Criteria) this;
        }

        public Criteria andIntegralLevelGreaterThanOrEqualTo(String value) {
            addCriterion("INTEGRAL_LEVEL >=", value, "integralLevel");
            return (Criteria) this;
        }

        public Criteria andIntegralLevelLessThan(String value) {
            addCriterion("INTEGRAL_LEVEL <", value, "integralLevel");
            return (Criteria) this;
        }

        public Criteria andIntegralLevelLessThanOrEqualTo(String value) {
            addCriterion("INTEGRAL_LEVEL <=", value, "integralLevel");
            return (Criteria) this;
        }

        public Criteria andIntegralLevelLike(String value) {
            addCriterion("INTEGRAL_LEVEL like", value, "integralLevel");
            return (Criteria) this;
        }

        public Criteria andIntegralLevelNotLike(String value) {
            addCriterion("INTEGRAL_LEVEL not like", value, "integralLevel");
            return (Criteria) this;
        }

        public Criteria andIntegralLevelIn(List<String> values) {
            addCriterion("INTEGRAL_LEVEL in", values, "integralLevel");
            return (Criteria) this;
        }

        public Criteria andIntegralLevelNotIn(List<String> values) {
            addCriterion("INTEGRAL_LEVEL not in", values, "integralLevel");
            return (Criteria) this;
        }

        public Criteria andIntegralLevelBetween(String value1, String value2) {
            addCriterion("INTEGRAL_LEVEL between", value1, value2, "integralLevel");
            return (Criteria) this;
        }

        public Criteria andIntegralLevelNotBetween(String value1, String value2) {
            addCriterion("INTEGRAL_LEVEL not between", value1, value2, "integralLevel");
            return (Criteria) this;
        }

        public Criteria andAccountCheckStatusIsNull() {
            addCriterion("ACCOUNT_CHECK_STATUS is null");
            return (Criteria) this;
        }

        public Criteria andAccountCheckStatusIsNotNull() {
            addCriterion("ACCOUNT_CHECK_STATUS is not null");
            return (Criteria) this;
        }

        public Criteria andAccountCheckStatusEqualTo(String value) {
            addCriterion("ACCOUNT_CHECK_STATUS =", value, "accountCheckStatus");
            return (Criteria) this;
        }

        public Criteria andAccountCheckStatusNotEqualTo(String value) {
            addCriterion("ACCOUNT_CHECK_STATUS <>", value, "accountCheckStatus");
            return (Criteria) this;
        }

        public Criteria andAccountCheckStatusGreaterThan(String value) {
            addCriterion("ACCOUNT_CHECK_STATUS >", value, "accountCheckStatus");
            return (Criteria) this;
        }

        public Criteria andAccountCheckStatusGreaterThanOrEqualTo(String value) {
            addCriterion("ACCOUNT_CHECK_STATUS >=", value, "accountCheckStatus");
            return (Criteria) this;
        }

        public Criteria andAccountCheckStatusLessThan(String value) {
            addCriterion("ACCOUNT_CHECK_STATUS <", value, "accountCheckStatus");
            return (Criteria) this;
        }

        public Criteria andAccountCheckStatusLessThanOrEqualTo(String value) {
            addCriterion("ACCOUNT_CHECK_STATUS <=", value, "accountCheckStatus");
            return (Criteria) this;
        }

        public Criteria andAccountCheckStatusLike(String value) {
            addCriterion("ACCOUNT_CHECK_STATUS like", value, "accountCheckStatus");
            return (Criteria) this;
        }

        public Criteria andAccountCheckStatusNotLike(String value) {
            addCriterion("ACCOUNT_CHECK_STATUS not like", value, "accountCheckStatus");
            return (Criteria) this;
        }

        public Criteria andAccountCheckStatusIn(List<String> values) {
            addCriterion("ACCOUNT_CHECK_STATUS in", values, "accountCheckStatus");
            return (Criteria) this;
        }

        public Criteria andAccountCheckStatusNotIn(List<String> values) {
            addCriterion("ACCOUNT_CHECK_STATUS not in", values, "accountCheckStatus");
            return (Criteria) this;
        }

        public Criteria andAccountCheckStatusBetween(String value1, String value2) {
            addCriterion("ACCOUNT_CHECK_STATUS between", value1, value2, "accountCheckStatus");
            return (Criteria) this;
        }

        public Criteria andAccountCheckStatusNotBetween(String value1, String value2) {
            addCriterion("ACCOUNT_CHECK_STATUS not between", value1, value2, "accountCheckStatus");
            return (Criteria) this;
        }

        public Criteria andAccountDateIsNull() {
            addCriterion("ACCOUNT_DATE is null");
            return (Criteria) this;
        }

        public Criteria andAccountDateIsNotNull() {
            addCriterion("ACCOUNT_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andAccountDateEqualTo(Date value) {
            addCriterionForJDBCDate("ACCOUNT_DATE =", value, "accountDate");
            return (Criteria) this;
        }

        public Criteria andAccountDateNotEqualTo(Date value) {
            addCriterionForJDBCDate("ACCOUNT_DATE <>", value, "accountDate");
            return (Criteria) this;
        }

        public Criteria andAccountDateGreaterThan(Date value) {
            addCriterionForJDBCDate("ACCOUNT_DATE >", value, "accountDate");
            return (Criteria) this;
        }

        public Criteria andAccountDateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("ACCOUNT_DATE >=", value, "accountDate");
            return (Criteria) this;
        }

        public Criteria andAccountDateLessThan(Date value) {
            addCriterionForJDBCDate("ACCOUNT_DATE <", value, "accountDate");
            return (Criteria) this;
        }

        public Criteria andAccountDateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("ACCOUNT_DATE <=", value, "accountDate");
            return (Criteria) this;
        }

        public Criteria andAccountDateIn(List<Date> values) {
            addCriterionForJDBCDate("ACCOUNT_DATE in", values, "accountDate");
            return (Criteria) this;
        }

        public Criteria andAccountDateNotIn(List<Date> values) {
            addCriterionForJDBCDate("ACCOUNT_DATE not in", values, "accountDate");
            return (Criteria) this;
        }

        public Criteria andAccountDateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("ACCOUNT_DATE between", value1, value2, "accountDate");
            return (Criteria) this;
        }

        public Criteria andAccountDateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("ACCOUNT_DATE not between", value1, value2, "accountDate");
            return (Criteria) this;
        }

        public Criteria andUpdateMoblieStatusIsNull() {
            addCriterion("UPDATE_MOBLIE_STATUS is null");
            return (Criteria) this;
        }

        public Criteria andUpdateMoblieStatusIsNotNull() {
            addCriterion("UPDATE_MOBLIE_STATUS is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateMoblieStatusEqualTo(String value) {
            addCriterion("UPDATE_MOBLIE_STATUS =", value, "updateMoblieStatus");
            return (Criteria) this;
        }

        public Criteria andUpdateMoblieStatusNotEqualTo(String value) {
            addCriterion("UPDATE_MOBLIE_STATUS <>", value, "updateMoblieStatus");
            return (Criteria) this;
        }

        public Criteria andUpdateMoblieStatusGreaterThan(String value) {
            addCriterion("UPDATE_MOBLIE_STATUS >", value, "updateMoblieStatus");
            return (Criteria) this;
        }

        public Criteria andUpdateMoblieStatusGreaterThanOrEqualTo(String value) {
            addCriterion("UPDATE_MOBLIE_STATUS >=", value, "updateMoblieStatus");
            return (Criteria) this;
        }

        public Criteria andUpdateMoblieStatusLessThan(String value) {
            addCriterion("UPDATE_MOBLIE_STATUS <", value, "updateMoblieStatus");
            return (Criteria) this;
        }

        public Criteria andUpdateMoblieStatusLessThanOrEqualTo(String value) {
            addCriterion("UPDATE_MOBLIE_STATUS <=", value, "updateMoblieStatus");
            return (Criteria) this;
        }

        public Criteria andUpdateMoblieStatusLike(String value) {
            addCriterion("UPDATE_MOBLIE_STATUS like", value, "updateMoblieStatus");
            return (Criteria) this;
        }

        public Criteria andUpdateMoblieStatusNotLike(String value) {
            addCriterion("UPDATE_MOBLIE_STATUS not like", value, "updateMoblieStatus");
            return (Criteria) this;
        }

        public Criteria andUpdateMoblieStatusIn(List<String> values) {
            addCriterion("UPDATE_MOBLIE_STATUS in", values, "updateMoblieStatus");
            return (Criteria) this;
        }

        public Criteria andUpdateMoblieStatusNotIn(List<String> values) {
            addCriterion("UPDATE_MOBLIE_STATUS not in", values, "updateMoblieStatus");
            return (Criteria) this;
        }

        public Criteria andUpdateMoblieStatusBetween(String value1, String value2) {
            addCriterion("UPDATE_MOBLIE_STATUS between", value1, value2, "updateMoblieStatus");
            return (Criteria) this;
        }

        public Criteria andUpdateMoblieStatusNotBetween(String value1, String value2) {
            addCriterion("UPDATE_MOBLIE_STATUS not between", value1, value2, "updateMoblieStatus");
            return (Criteria) this;
        }

        public Criteria andIsBlackListIsNull() {
            addCriterion("IS_BLACK_LIST is null");
            return (Criteria) this;
        }

        public Criteria andIsBlackListIsNotNull() {
            addCriterion("IS_BLACK_LIST is not null");
            return (Criteria) this;
        }

        public Criteria andIsBlackListEqualTo(String value) {
            addCriterion("IS_BLACK_LIST =", value, "isBlackList");
            return (Criteria) this;
        }

        public Criteria andIsBlackListNotEqualTo(String value) {
            addCriterion("IS_BLACK_LIST <>", value, "isBlackList");
            return (Criteria) this;
        }

        public Criteria andIsBlackListGreaterThan(String value) {
            addCriterion("IS_BLACK_LIST >", value, "isBlackList");
            return (Criteria) this;
        }

        public Criteria andIsBlackListGreaterThanOrEqualTo(String value) {
            addCriterion("IS_BLACK_LIST >=", value, "isBlackList");
            return (Criteria) this;
        }

        public Criteria andIsBlackListLessThan(String value) {
            addCriterion("IS_BLACK_LIST <", value, "isBlackList");
            return (Criteria) this;
        }

        public Criteria andIsBlackListLessThanOrEqualTo(String value) {
            addCriterion("IS_BLACK_LIST <=", value, "isBlackList");
            return (Criteria) this;
        }

        public Criteria andIsBlackListLike(String value) {
            addCriterion("IS_BLACK_LIST like", value, "isBlackList");
            return (Criteria) this;
        }

        public Criteria andIsBlackListNotLike(String value) {
            addCriterion("IS_BLACK_LIST not like", value, "isBlackList");
            return (Criteria) this;
        }

        public Criteria andIsBlackListIn(List<String> values) {
            addCriterion("IS_BLACK_LIST in", values, "isBlackList");
            return (Criteria) this;
        }

        public Criteria andIsBlackListNotIn(List<String> values) {
            addCriterion("IS_BLACK_LIST not in", values, "isBlackList");
            return (Criteria) this;
        }

        public Criteria andIsBlackListBetween(String value1, String value2) {
            addCriterion("IS_BLACK_LIST between", value1, value2, "isBlackList");
            return (Criteria) this;
        }

        public Criteria andIsBlackListNotBetween(String value1, String value2) {
            addCriterion("IS_BLACK_LIST not between", value1, value2, "isBlackList");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table usercore_user_register
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table usercore_user_register
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}