package com.example.demo.bean;

import java.io.Serializable;

public class UsercoreUserRegisterKey implements Serializable {
    /**  */
    private static final long serialVersionUID = -2071473832818607596L;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usercore_user_register.TENANT_ID
     *
     * @mbggenerated
     */
    private String tenantId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usercore_user_register.USER_NO
     *
     * @mbggenerated
     */
    private String userNo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usercore_user_register.TENANT_ID
     *
     * @return the value of usercore_user_register.TENANT_ID
     *
     * @mbggenerated
     */
    public String getTenantId() {
        return tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usercore_user_register.TENANT_ID
     *
     * @param tenantId the value for usercore_user_register.TENANT_ID
     *
     * @mbggenerated
     */
    public void setTenantId(String tenantId) {
        this.tenantId = tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usercore_user_register.USER_NO
     *
     * @return the value of usercore_user_register.USER_NO
     *
     * @mbggenerated
     */
    public String getUserNo() {
        return userNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usercore_user_register.USER_NO
     *
     * @param userNo the value for usercore_user_register.USER_NO
     *
     * @mbggenerated
     */
    public void setUserNo(String userNo) {
        this.userNo = userNo;
    }
}