package com.example.demo.dao;

import com.example.demo.bean.UsercoreUserRegister;
import com.example.demo.bean.UsercoreUserRegisterExample;
import com.example.demo.bean.UsercoreUserRegisterKey;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@Mapper
public interface UsercoreUserRegisterMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usercore_user_register
     *
     * @mbggenerated
     */
    int countByExample(UsercoreUserRegisterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usercore_user_register
     *
     * @mbggenerated
     */
    int deleteByExample(UsercoreUserRegisterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usercore_user_register
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(UsercoreUserRegisterKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usercore_user_register
     *
     * @mbggenerated
     */
    int insert(UsercoreUserRegister record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usercore_user_register
     *
     * @mbggenerated
     */
    int insertSelective(UsercoreUserRegister record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usercore_user_register
     *
     * @mbggenerated
     */
    List<UsercoreUserRegister> selectByExample(UsercoreUserRegisterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usercore_user_register
     *
     * @mbggenerated
     */
    UsercoreUserRegister selectByPrimaryKey(UsercoreUserRegisterKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usercore_user_register
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") UsercoreUserRegister record, @Param("example") UsercoreUserRegisterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usercore_user_register
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") UsercoreUserRegister record, @Param("example") UsercoreUserRegisterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usercore_user_register
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(UsercoreUserRegister record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usercore_user_register
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(UsercoreUserRegister record);
}